apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanak81-apideveloper-certificate
  namespace: thanak81-apideveloper
spec:
  secretName: thanak81-apideveloper-secret-tls
  commonName: thanak81-apideveloper.assessify.org
  dnsNames:
  - thanak81-apideveloper.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
